base:
  project: bigmart-salespred-project
  random_state: 10
  target_col: Item_Outlet_Sales

data_source: 
  data_source_train: data/data_given/Train.csv
  data_source_test: data/data_given/Test.csv

load_data:
  raw_train_csv: data/raw/raw_train.csv
  raw__test_csv: data/raw/raw_test.csv

split_data:
  train_path: data/processed/train_modified.csv
  test_path: data/processed/test_modified.csv
  test_size: 0.2